image: node:14.15.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

test:
  variables:
    COUCHDB_HOST: couchdb
    COUCHDB_PORT: 5984
    COUCHDB_URL: http://$COUCHDB_HOST:$COUCHDB_PORT/
    COUCHDB_USER: admin
    COUCHDB_PASSWORD: "admin"
    DBNAME: testdb

  services:
    - couchdb:latest

  before_script:
    - npm config set @concordant:registry "https://gitlab.inria.fr/api/v4/packages/npm/"
    - npm config set '//gitlab.inria.fr/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm install
    - npm ci --cache .npm --prefer-offline
    - curl -u "$COUCHDB_USER:$COUCHDB_PASSWORD"
      -X PUT $COUCHDB_URL/_users
    - curl -u "$COUCHDB_USER:$COUCHDB_PASSWORD"
      -X PUT $COUCHDB_URL/$DBNAME

  script:
    - npm test

  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
