openapi: 3.0.0
info:
  title: "Concordant API"
  version: 1.0.0
paths: {}
components:
  schemas:
    Query:
      type: object
      properties:
        getObjects:
          type: array
          items:
            type: string
        getObject:
          type: string
        replicators:
          type: array
          items:
            $ref: "#/components/schemas/Replicator"
        replicator:
          $ref: "#/components/schemas/Replicator"
    Replicator:
      type: object
      required:
        - id
      properties:
        id:
          type: object
        source:
          type: string
        target:
          type: string
        continuous:
          type: boolean
        state:
          type: string
    Mutation:
      type: object
      properties:
        createApp:
          type: string
        deleteApp:
          type: string
        updateObject:
          type: string
        replicator:
          type: string
